### ISSUE TITLE
Dependencies are not being passed to the TestFilter external process.

### ISSUE THREAD

**Issue by bartoszzuk** [yyxhdy/arja#13]
Unfortunately same issue as #12. Dependencies are not being passed to the TestFilter, bacause of the buggy if statment condition (unnecessary negation).

https://github.com/yyxhdy/arja/blob/c34e400ed500a0628639f3c798209267933453e5/src/main/java/us/msu/cse/repair/core/coverage/TestFilterProcess.java#L66-L73

Resulting in **NoClassDefFoundError** being thrown and all positive tests being filtered.

![OtherBug](https://user-images.githubusercontent.com/57541034/103461309-a7d3d480-4d1d-11eb-8d10-4c4ca3d01b45.png)

**Comment by yyxhdy** [comment]
Hi, can you provide me more details so that I can reproduce this issue?

**Comment by bartoszzuk** [comment]
Hi,
I was testing ARJA on simple concurrent programs and used some 
additional dependencies (other than the JUnit ones). You can view the project [here](https://github.com/bartoszzuk/BrokenPeterson). 
Some tests are nondeterministic, but at least three are always positive.
They all cover faulty lines and should not be filtered out.

They were

![Faulty](https://user-images.githubusercontent.com/57541034/104104849-d6682700-52aa-11eb-939c-6114391d8672.png)

but when I removed the negation, they were kept.

![Correct](https://user-images.githubusercontent.com/57541034/104104853-de27cb80-52aa-11eb-99a6-f2cd5f6c5d1c.png)

**Comment by yyxhdy** [comment]
Thanks so much for pointing out this bug! I have created a new commit to fix this. Please see here:
https://github.com/yyxhdy/arja/commit/e7950328c05e3f7eb38e1af11efc31055af09d05

**Comment by bartoszzuk** [comment]
Happy to help :)
