### ISSUE TITLE
Can ARJAE save generated repaired programs instead of patches?

### ISSUE THREAD

**Issue by Amirfarhad-Nilizadeh** [yyxhdy/arja#15]
When I use ARJAE, it saves patches in a pool directory, but not the repaired program with applied generated patches.

Is any option available in the ARJAE framework that saves a repaired program instead of saving patches?  Insert patches manually into a program makes it difficult to use for large studies.

**Comment by yyxhdy** [comment]
Hi, ARJA-e does not output repaired programs. But you can use -DdiffFormat argument, and  the output patch is a file generated by "diff -u\" and you can easily apply this patch to the original program to get the patched program. 

See  "-DdiffFormat"  in this file https://github.com/yyxhdy/arja/blob/arja-e/src/us/msu/cse/repair/ParameterInfoMain.java at line 30.

If you really wants to save the repaired program directly, you can add several lines of code in the method
public void saveTestAdequatePatch(List<Integer> opList, List<Integer> locList, List<Integer> ingredList,
			Map<String, String> modifiedJavaSources) throws IOException 
in the file https://github.com/yyxhdy/arja/blob/arja-e/src/us/msu/cse/repair/core/AbstractRepairProblem.java.

The map modifiedJavaSources store the modified java files, just save them to the files at the beginning of this method.

**Comment by Amirfarhad-Nilizadeh** [comment]
Hi,

I appreciate your help. When I use "-DdiffFormat true" then it provides both diff changes and the repaired program (as I needed).
