### ISSUE TITLE
java.lang.NoClassDefFoundError error

### ISSUE THREAD

**Issue by Somdutta** [yyxhdy/arja#2]
Hi,

I am running ARJA on macOS High Sierra. I have written a java file and a junit test file to test that Java program. Following is the command that I am running
java -cp lib/*:bin us.msu.cse.repair.Main Arja -DsrcJavaDir /Users/somdutta/eclipse-workspace/ECS289C/GCD/src/org/gcd -DbinJavaDir /Users/somdutta/eclipse-workspace/ECS289C/GCD/bin/org/gcd -DbinTestDir /Users/somdutta/eclipse-workspace/ECS289C/GCD/bin/org/gcd/test -Ddependences /Users/somdutta/.p2/pool/plugins

The error that I am getting is 
Exception in thread "main" java.lang.NoClassDefFoundError: org/gcd/test/GCDTest (wrong name: GCDTest)

I am giving the right path where the class file of the JUnit test file for -DbinTestDir. Could you please let me know if I am running the tool properly?

Thanks

**Comment by yyxhdy** [comment]
Hi, can you show me your source code and JUnit test code?

**Comment by Somdutta** [comment]
It's not allowing to attach .java files here. How do I share it with you?

**Comment by yyxhdy** [comment]
If possible, please just zip your GCD folder and send it to yyxhdy at gmail.com.

**Comment by Somdutta** [comment]
I've sent it.

**Comment by yyxhdy** [comment]
There is something wrong in the paths you set, please try the following. For -Ddependences, find the paths of Junit jars in your computer. 

-DsrcJavaDir /Users/somdutta/eclipse-workspace/ECS289C/GCD/src
-DbinJavaDir /Users/somdutta/eclipse-workspace/ECS289C/GCD/bin
-DbinTestDir /Users/somdutta/eclipse-workspace/ECS289C/GCD/bin
-Ddependences /Users/.../junit-4.11.jar:/Users/.../hamcrest-core-1.3.jar

**Comment by Somdutta** [comment]
Thanks, I am able to run the tool without the errors that I was getting before.
However, could you please let me know if I am running it in a correct manner? By that I mean is the JUnit test case is what the tool expects as compiled test code? Where will the repair files be created if there is an error in the source code. How do I provide +ve and -ve test cases?

**Comment by yyxhdy** [comment]
The tool will use the compiled JUNIT test code and you can just use -DbinTestDir to specify where it is. In your example, you put your compiled source code and test code in the same root directory, so -DbinJavaDir and -DbinTestDir are the same. If the tool can find a patch (i.e., make all the tests pass), it will output patches in the directory arja/patches_$id$ by default, where $id$ is a randomly generated string containing four characters. You can just write JUNIT test cases to provide positive and negative test cases.

**Comment by Somdutta** [comment]
I introduced a bug in my source code (GCD.java) and my JUnit test case (1 test case) is such that it will fail for a particular input. So, if I run ARJA, arja/patches_$id$ should be generated. As, of now when I run the tool, there are no errors on console, but I don't see any patches getting generated. Let me know if I doing something wrong. If you have any test project which can serve as a guide it will also be helpful. Thanks.

**Comment by yyxhdy** [comment]
This tool is basically based on an assumption that your fix statement is in the buggy program. However, this assumption may not hold for very small programs where the statement-level redundancy may not exist. So check that if your program can be fixed in this way. If you want to verify whether the tool works normally, a simpler method is to generate a bug in your program by adding a redundant statement, and ARJA should return a patch containing a deletion.

**Comment by Somdutta** [comment]
I've sent you a source at yyxhdy@gmail.com with a bug. Could you please let me know if the tool will fix this bug. Details are in the email.
