### ISSUE TITLE
Is there any argument/option to force Arja to only consider a given set of tests?

### ISSUE THREAD

**Issue by jose** [yyxhdy/arja#9]
Hi,

Repair frameworks such as [astor](https://github.com/SpoonLabs/astor), [nopol](https://github.com/SpoonLabs/nopol), and [npefix](https://github.com/SpoonLabs/npefix) can be instantiated with a defined set of tests.  For the [astor](https://github.com/SpoonLabs/astor/blob/master/docs/getting-starting.md#command-line-arguments) repair framework the argument is `-failing`, and for [nopol](https://github.com/SpoonLabs/nopol#minimal-usage) and [npefix](https://github.com/SpoonLabs/npefix#command-line) is `--test`.  Is there any similar argument/option for Arja?

--
Best,
Jose

**Comment by yyxhdy** [comment]
Hi Jose,

I just added an argument -Dtests to support the functionality you mentioned. Please let me know whether it works.

Thanks!

**Comment by jose** [comment]
Yes, it does.  Thanks.
